version: "3.8"
networks:
  digital-twin-service:
    driver: bridge
x-hosts: &hosts
    - niryo-one-master:127.0.0.1
    - niryo-one-drivers:127.0.0.1
    - niryo-one-stack:127.0.0.1
    - niryo-one-dtwin:127.0.0.1
    - niryo-one-web:127.0.0.1
x-ros-config: &ros-config
    - ROS_MASTER_URI=http://127.0.0.1:11311
services:
  master:
    image: niryo-ros-master:latest
    hostname: niryo-one-master
    build: ../../../digital-twin-service/ros-master/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
  drivers:
    image: niryo-sim-drivers:latest
    hostname: niryo-one-drivers
    build: ../../../digital-twin-service/niryo-one-drivers/simulation/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
  robot-stack:
    image: niryo-one-full-stack:latest
    hostname: niryo-one-stack
    build: ../../../digital-twin-service/niryo-one-stack/niryo-one-stack/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
      - drivers
  dtwin:
    image: niryo-one-dtwin:latest
    hostname: niryo-one-dtwin
    build: ../../../digital-twin-service/digital-replica/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
      - drivers
      - robot-stack
  web:
    image: niryo-one-web:latest
    hostname: niryo-one-web
    build: ../../../digital-twin-service/web-interface/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
      - drivers
      - robot-stack
# zenoh-router:
#    image:
#    name:
#    ports:
#      - 7447:7447/tcp
#      - 7447:7447/udp
#      - 8000:8000/tcp
#    network: 169.254.210.7
#  replay:
#    image:
#    build:
#    env_file:
#      - replay.env
#    ports:
#     - 5000:5000
#    extra_hosts: *hosts
