version: "3.8"
networks:
  digital-twin-service:
    ipam: 
      driver: default
      config: 
        - subnet: "172.23.0.0/16"
x-hosts: &hosts
    - niryo-one-master:127.0.0.1
    - niryo-one-drivers:127.0.0.1
    - niryo-one-control:127.0.0.1
    - niryo-one-motion:127.0.0.1
    - niryo-one-interface:127.0.0.1
    - niryo-one-dtwin:127.0.0.1
    - niryo-one-web:127.0.0.1
x-ros-config: &ros-config
    - ROS_MASTER_URI=http://127.0.0.1:11311
services:
  master:
    image: niryo-ros-master:latest
    hostname: niryo-one-master
    build: ../../../digital-twin-service/ros-master/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
  drivers:
    image: niryo-sim-drivers:latest
    hostname: niryo-one-drivers
    build: ../../../digital-twin-service/niryo-one-drivers/simulation/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
  control:
    image: niryo-one-control:latest
    hostname: niryo-one-control
    build: ../../../digital-twin-service/niryo-one-stack/niryo-one-control/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
      - drivers
  motion:
    image: niryo-one-motion:latest
    hostname: niryo-one-motion
    build: ../../../digital-twin-service/niryo-one-stack/niryo-one-motion/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
      - drivers
      - control
  interface:
   image: niryo-one-interface:latest
   hostname: niryo-one-motion
   build: ../../../digital-twin-service/niryo-one-stack/niryo-one-interface/
   environment: *ros-config
   extra_hosts: *hosts
   network_mode: host
   depends_on:
     - master
     - drivers
     - control
     - motion
  dtwin:
    image: niryo-one-dtwin:latest
    hostname: niryo-one-dtwin
    build: ../../../digital-twin-service/digital-replica/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
      - drivers
      - control
      - motion
      - interface
  web:
    image: niryo-one-web:latest
    hostname: niryo-one-web
    build: ../../../digital-twin-service/web-interface/
    environment: *ros-config
    extra_hosts: *hosts
    network_mode: host
    depends_on:
      - master
      - drivers
      - control
      - motion
      - interface
      - dtwin
  zenoh:
    image: eclipse/zenoh:0.5.0-beta.5
    ports:
      - 7447:7447/tcp
      - 7447:7447/udp
      - 8000:8000/tcp
    networks:
      digital-twin-service:
        ipv4_address: 172.23.0.2
     
  replay:
    image: zenoh-replay:latest
    ports: 
      - 5000:5000
    environment: 
      - ZENOH_ROUTER_ADDRESS=tcp/172.23.0.2:7447
      - REPLICA_ROS_TOPIC=/coppeliaSIM/NiryoOne1/joint_states1
      - ROS_MASTER_URI=http://127.0.0.1:11311/ # embed this with x-enviornment
    extra_hosts: *hosts
    networks:
      digital-twin-service:
        ipv4_address: 172.23.0.3
    depends_on:  
      - master
      - drivers
      - control
      - motion
      - interface
      - dtwin
      - zenoh
